### Introduction

- Numpy is the main library for Numerical Computing in Python.
- All Matrix operations can be performed using Numpy
- It has optimized and vectorized implementations of all operations that can be performed on a Tensor (Multi-dimensional Array)


In [1]:
# Import the library
import numpy as np

### Different ways of creating numpy array

#### Method 1: Using a Python list
 Description: Create a numpy array from a Python list.
 - Example usage:   
    arr = np.array([1, 2, 3, 4, 5])  
    print(arr)  # Output: [1 2 3 4 5]  
    

#### Method 2: Using numpy functions
 Description: Create a numpy array using numpy functions like zeros, ones, arange, etc.
 - Example usage:  
   arr = np.zeros((3, 3))  
   print(arr)  # Output: [[0. 0. 0.]  
                         [0. 0. 0.]  
                         [0. 0. 0.]]  

#### Method 3: Using random numbers
 Description: Create a numpy array with random numbers using numpy's random module.
 - Example usage:   
   arr = np.random.rand(5)  
   print(arr)  # Output: [0.12345678 0.98765432 0.54321098 0.87654321 0.23456789]


### Creating Numpy Arrays from Lists and other numpy arrays

In [8]:
# Define a dummy array for 1-D
arr1 = np.array([1, 2, 3, 4, 5])   # 1-D array initialization from a list
print("1-D Array: ", arr1)

# Define a dummy array for 2-D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])   # 2-D array initialization from a list of lists
print("2-D Array: ", arr2)

# Define a dummy array for 3-D
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # 3-D array initialization from a list of lists of lists
print("3-D Array: ", arr3)

#Define a numpy array using arr1
arr4 = np.array([arr1, arr1, arr1])   # 2-D array initialization from a list of 1-D arrays
print("2-D Array from 1-D Array: ", arr4)

#Define a numpy array using arr1 and a list
arr5 = np.array([arr1, [6, 7, 8, 9, 10]])   # 2-D array initialization from a list of 1-D arrays and a list
print("2-D Array from 1-D Array and List: ", arr5)

1-D Array:  [1 2 3 4 5]
2-D Array:  [[1 2 3]
 [4 5 6]]
3-D Array:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2-D Array from 1-D Array:  [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
2-D Array from 1-D Array and List:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Creating Numpy Arrays using Numpy Functions
- **empty()**
- **zeros()**
- **ones()**
- **full()**
- **eye()**
- **arange()**

In [17]:
#Define a numpy array using empty() function
arr_empty = np.empty((3, 3))
print("Empty Array: ", arr_empty)

#Define a numpy array using empty() function with dtype as int
arr_empty_int = np.empty((3, 3), dtype=int)
print("Empty Array with dtype as int: ", arr_empty_int)

#Define a numpy array using zeros() function
arr_zeros = np.zeros((3, 3))  # 3x3 array with all elements as 0
print("Zeros Array: ", arr_zeros)

#Define a numpy array using ones() function
arr_ones = np.ones((3, 3))  # 3x3 array with all elements as 1
print("Ones Array: ", arr_ones)

#Define a numpy array using full() function
arr_full = np.full((3, 3), 5)  # 3x3 array with all elements as 5
print("Full Array: ", arr_full)

#Define a numpy array using eye() function
arr_eye = np.eye(3) # 3x3 identity matrix
print("Identity Matrix: ", arr_eye)

#Define a numpy array using arange() function
arr_arange = np.arange(0, 10, 2)  # 0 to 10 with a step of 2
print("Array using arange(): ", arr_arange)

#Define a numpy array using linspace() function
arr_linspace = np.linspace(0, 10, 5)   # 5 elements between 0 and 10 that are equally spaced
print("Array using linspace(): ", arr_linspace)



Empty Array:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Empty Array with dtype as int:  [[4 1 4]
 [1 2 2]
 [0 1 1]]
Zeros Array:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Array:  [[5 5 5]
 [5 5 5]
 [5 5 5]]
Identity Matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array using arange():  [0 2 4 6 8]
Array using linspace():  [ 0.   2.5  5.   7.5 10. ]


### Creating Numpy Arrays Using Random Functions

Numpy provides several functions to create arrays:

- **`numpy.random.rand()`**: This function creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1).
- **`numpy.random.randn()`**: This function returns a sample (or samples) from the "standard normal" distribution.
- **`numpy.random.randint()`**: This function returns random integers from the "discrete uniform" distribution in the "half-open" interval [low, high).
- **`numpy.random.random_sample()`**: This function returns random floats in the half-open interval [0.0, 1.0).
- **`numpy.random.choice()`**: This function generates a random sample from a given 1-D array.

In [14]:
# Define a numpy array using random.rand() function
arr_rand = np.random.rand(3, 3)  # 3x3 array with random values between 0 and 1
print("Random Array: ", arr_rand)

# Define a numpy array using random.randn() function
arr_randn = np.random.randn(3, 3)  # 3x3 array with random values from a normal distribution
print("Random Normal Array: ", arr_randn)

# Define a numpy array using random.randint() function
arr_randint = np.random.randint(0, 10, (3, 3))  # 3x3 array with random integers between 0 and 10
print("Random Integer Array: ", arr_randint)

# Define a numpy array using random.choice() function
arr_choice = np.random.choice([1, 2, 3, 4, 5], (3, 3))  # 3x3 array with random values from the given list
print("Random Choice Array: ", arr_choice)

# Define a numpy array using random.seed() function
np.random.seed(0)  # Seed the random number generator
arr_seed = np.random.rand(3, 3)  # 3x3 array with random values between 0 and 1
print("Random Seed Array: ", arr_seed)

Random Array:  [[0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]]
Random Normal Array:  [[ 0.44386323  0.33367433  1.49407907]
 [-0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362 ]]
Random Integer Array:  [[7 2 0]
 [0 4 5]
 [5 6 8]]
Random Choice Array:  [[5 2 5]
 [2 3 3]
 [1 2 2]]
Random Seed Array:  [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


### Creating Numpy Arrays Using Like Functions

Numpy provides several functions to create arrays that are "like" other arrays:

- **`numpy.zeros_like()`**: This function returns an array of zeros with the same shape and type as a given array.
- **`numpy.ones_like()`**: This function returns an array of ones with the same shape and type as a given array.
- **`numpy.empty_like()`**: This function returns a new array with the same shape and type as a given array, without initializing entries.
- **`numpy.full_like()`**: This function returns a new array with the same shape and type as a given array, filled with a fill value.

In [15]:
# Define a numpy array of (2,2) with list of lists
dummy = np.array([[1, 2], [3, 4]])

# Define a numpy array using zeros_like() function
arr_zeros_like = np.zeros_like(dummy)  # 2x2 array with all elements as 0
print("Zeros Like Array: ", arr_zeros_like)

# Define a numpy array using ones_like() function
arr_ones_like = np.ones_like(dummy)  # 2x2 array with all elements as 1
print("Ones Like Array: ", arr_ones_like)

# Define a numpy array using full_like() function
arr_full_like = np.full_like(dummy, 5)  # 2x2 array with all elements as 5
print("Full Like Array: ", arr_full_like)

# Define a numpy array using empty_like() function
arr_empty_like = np.empty_like(dummy)  # 2x2 array with random values
print("Empty Like Array: ", arr_empty_like)

Zeros Like Array:  [[0 0]
 [0 0]]
Ones Like Array:  [[1 1]
 [1 1]]
Full Like Array:  [[5 5]
 [5 5]]
Empty Like Array:  [[-1464094608         332]
 [          0           0]]


### Attributes of a Numpy Array

A Numpy array has several attributes:

- **`numpy.ndarray.shape`**: This attribute returns a tuple representing the dimensions of the array.
- **`numpy.ndarray.size`**: This attribute returns the total number of elements of the array.
- **`numpy.ndarray.ndim`**: This attribute returns the number of array dimensions. This is nothing but rank.
- **`numpy.ndarray.dtype`**: This attribute returns the data type of the array elements.
- **`numpy.ndarray.itemsize`**: This attribute returns the length of one array element in bytes.
- **`numpy.ndarray.nbytes`**: This attribute returns the total size of the array
- **`numpy.ndarray.data`**: This attribute returns the buffer containing the actual elements of the array.

In [18]:
# Define a numpy array of (3,3) with list of lists
dummy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the shape of the array
print("Shape of the array: ", dummy.shape)

# Get the number of dimensions of the array
print("Number of dimensions of the array: ", dummy.ndim)

# Get the number of elements in the array
print("Number of elements in the array: ", dummy.size)

# Get the data type of the elements in the array
print("Data type of the elements in the array: ", dummy.dtype)

# Get the size of the elements in the array
print("Size of the elements in the array: ", dummy.itemsize)

# Get the total size of the array
print("Total size of the array: ", dummy.nbytes)

# SHow data buffer of the array
print("Data buffer of the array: ", dummy.data)


Shape of the array:  (3, 3)
Number of dimensions of the array:  2
Number of elements in the array:  9
Data type of the elements in the array:  int32
Size of the elements in the array:  4
Total size of the array:  36
Data buffer of the array:  <memory at 0x0000014CAA4F9080>
